image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python'
    command: 'poetry completions bash > /etc/bash_completion.d/poetry.bash-completion'
