[tool.poetry]
name = "auth0-test"
version = "0.1.0"
description = ""
authors = ["bergmito"]

[tool.poetry.dependencies]
python = "3.8.*"
fastapi = "0.58.1"
uvicorn = "0.11.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
